-- Migration: Criar tabelas bancos_ativos e especies_ativas para configuracao dinamica
-- Criado em: 2026-07-10

-- 1. TABELA DE BANCOS ATIVOS
create table if not exists public.bancos_ativos (
  id bigint generated by default as identity primary key,
  nome text not null unique,
  ativo boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.bancos_ativos enable row level security;

-- Políticas de RLS
create policy "Allow read for all users" on public.bancos_ativos
  for select using (true);

create policy "Allow write for authenticated users" on public.bancos_ativos
  for all using (auth.role() = 'authenticated');

-- Seeding Inicial de Bancos
insert into public.bancos_ativos (nome) values
  ('ITAÚ'),
  ('BANCO PAN'),
  ('BMG'),
  ('C6 BANK'),
  ('BRADESCO'),
  ('BANRISUL'),
  ('DAYCOVAL'),
  ('AGIBANK'),
  ('SAFRA'),
  ('MERCANTIL'),
  ('MEU TUDO'),
  ('SANTANDER'),
  ('CAIXA ECONÔMICA')
on conflict (nome) do nothing;


-- 2. TABELA DE ESPÉCIES DE BENEFÍCIO ATIVAS
create table if not exists public.especies_ativas (
  id bigint generated by default as identity primary key,
  codigo text not null unique,
  descricao text not null,
  ativo boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Habilitar RLS
alter table public.especies_ativas enable row level security;

-- Políticas de RLS
create policy "Allow read for all users" on public.especies_ativas
  for select using (true);

create policy "Allow write for authenticated users" on public.especies_ativas
  for all using (auth.role() = 'authenticated');

-- Seeding Inicial de Espécies INSS
insert into public.especies_ativas (codigo, descricao) values
  ('41', 'Aposentadoria por Idade'),
  ('21', 'Pensão por Morte'),
  ('32', 'Aposentadoria por Invalidez (Previdenciária)'),
  ('88', 'Amparo Assistencial ao Idoso (BPC LOAS)'),
  ('87', 'Amparo Assistencial ao Portador de Deficiência (BPC LOAS)'),
  ('12', 'Aposentadoria por Invalidez por Acidente de Trabalho'),
  ('42', 'Aposentadoria por Tempo de Contribuição')
on conflict (codigo) do nothing;
